# Generated by Django 5.0.4 on 2024-06-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_exercise_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
